#ifndef COMMMC_APP_CONFIG_H
#define COMMMC_APP_CONFIG_H

#define COMMMC_APP_PIPE_DEPTH         12
#define COMMMC_APP_PERF_ID            0x64

#define COMMMC_APP_INIT_INF_EID 1
#define COMMMC_APP_INIT_ERR_EID 2
#define COMMMC_APP_PIPE_ERR_EID 3
#define COMMMC_APP_HK_SEND_ERR_EID 4
#define COMMMC_APP_MID_ERR_EID 5
#define COMMMC_APP_MSG_RECEIVED_EID 6
#define COMMMC_APP_MSG_SENT_EID 7
#define COMMMC_APP_CMD_ERR_EID 8

#define CFE_MISSION_COMMMC_APP_HK_TLM_TOPICID    0xA2
#define CFE_MISSION_COMMMC_APP_SEND_HK_TOPICID   0xB2
#define CFE_MISSION_COMMMC_APP_CMD_TOPICID       0xC2

#define COMMMC_APP_HK_TLM_MID  CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_COMMMC_APP_HK_TLM_TOPICID)
#define COMMMC_APP_SEND_HK_MID  CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_COMMMC_APP_SEND_HK_TOPICID)
#define COMMMC_APP_CMD_MID      CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_COMMMC_APP_CMD_TOPICID)


#endif /* COMMMC_APP_CONFIG_H */